name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Cypress spec pattern to run"
        required: false
        type: string
        default: "cypress/e2e/*"

jobs:
  chrome-tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:22.16.0
      options: --user 1001

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          wait-on: https://petlov.vercel.app
          browser: chrome
          group: Chrome
          record: true
          parallel: true
          spec: ${{ github.event.inputs.spec }}

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firefox-tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:22.16.0
      options: --user 1001

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          wait-on: https://petlov.vercel.app
          browser: firefox
          group: Firefox
          record: true
          parallel: true
          spec: ${{ github.event.inputs.spec }}

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
